spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/coupon
    username: root
    password: password
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

server:
  tomcat:
    threads:
      max: 1000
    accept-count: 10000
    max-connections: 10000